title: Armando JosÃ© Barsante Santos
author: Armando J. B. Santos
email: armando_barsante@msn.com
description: >-
Biologist focused on the conservation of wildlife and ecological systems.

theme: minima
