title: Armando JosÃ© Barsante Santos, PhD
email: armando_barsante@msn.com
description: >
  Biologist interested on the conservation of biodiversity and ecological processes.
theme: minima

# Custom navigation
header_pages:
  - index.md
  - cv.md
 # - index-pt.md #
#  - cv-pt.md #
- title: Google Scholar
    url: https://scholar.google.com/citations?user=vt0Yn70AAAAJ
